// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id_example"`
	Name      *string        `gorm:"column:name;type:varchar(20)" json:"name_example"`
	Age       *int64         `gorm:"column:age;type:bigint(20)" json:"age_example"`
	Birthday  *time.Time     `gorm:"column:birthday;type:datetime" json:"birthday_example"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime" json:"created_at_example"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime" json:"updated_at_example"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1" json:"deleted_at_example"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
